export type SectionPhase = 'live' | 'q1' | 'q2' | 'q3';

export interface ExploreSection {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  icon: string;
  phase: SectionPhase;
  category: string;
  features?: string[];
  whyItMatters?: string;
  vision?: string;
}

export const EXPLORE_CATEGORIES = [
  'Creation Studios',
  'Intelligence & Models',
  'Marketplace & Library',
  'Creator Economy',
  'Social & Community',
  'Collaboration & Workflow',
  'Admin & Enterprise',
  'Platform & Settings',
  'Support & Growth',
] as const;

export const CORE_SECTIONS: ExploreSection[] = [
  { slug: 'landing', name: 'Landing', tagline: 'The arrival experience', description: 'The multilingual cinematic front door to XeomX — where the world discovers the platform.', icon: 'Globe', phase: 'live', category: 'core', features: [] },
  { slug: 'login', name: 'The Awakening', tagline: 'Your cinematic entry point', description: 'Sign in to unlock the full XeomX universe.', icon: 'Sparkles', phase: 'live', category: 'core', features: [] },
  { slug: 'dashboard', name: 'Central Intelligence', tagline: 'Your command center', description: 'Monitor, manage and orchestrate everything from one place.', icon: 'LayoutDashboard', phase: 'live', category: 'core', features: [] },
  { slug: 'home', name: 'Home Feed', tagline: 'The pulse of XeomX', description: 'Discover trending prompts, viral content and premium drops.', icon: 'Home', phase: 'live', category: 'core', features: [] },
];

export const EXPLORE_SECTIONS: ExploreSection[] = [
  { slug: 'studio-canvas', name: 'Studio Canvas', tagline: 'The creative forge for AI artisans', description: 'Build, remix and perfect AI creations in a cinematic canvas environment.', icon: 'Palette', phase: 'q1', category: 'Creation Studios', features: ['Multi-modal canvas', 'Real-time AI generation', 'Layer system', 'Export in 4K'] },
  { slug: 'visual-workflow', name: 'Visual Workflow Builder', tagline: 'Drag. Connect. Create.', description: 'Build complex AI pipelines visually — no code required.', icon: 'GitBranch', phase: 'q1', category: 'Creation Studios', features: ['Node-based editor', '50+ AI connectors', 'One-click deploy', 'Template library'] },
  { slug: 'video-studio', name: 'Video Studio', tagline: 'Cinema-grade AI video creation', description: 'Generate, edit and produce professional video content with AI.', icon: 'Video', phase: 'q2', category: 'Creation Studios', whyItMatters: 'Video is the dominant medium of 2026. XeomX Video Studio puts Hollywood-quality production in your hands.' },
  { slug: 'coding-studio', name: 'Coding Studio', tagline: 'AI-powered development environment', description: 'Write, test and deploy code with AI assistance at every step.', icon: 'Code2', phase: 'q1', category: 'Creation Studios', features: ['Multi-language support', 'AI autocomplete', 'Live preview', 'One-click deploy'] },
  { slug: 'app-builder', name: 'App/Site/Game Builder', tagline: 'Build anything. Ship instantly.', description: 'Create full applications, websites and games using AI — from idea to production in minutes.', icon: 'Layers', phase: 'q2', category: 'Creation Studios', whyItMatters: 'The barrier to building software is now zero. XeomX App Builder lets anyone create professional digital products.' },
  { slug: '3d-avatar-studio', name: '3D / Avatar Studio', tagline: 'Your digital identity, reimagined', description: 'Create photorealistic 3D avatars and environments with AI.', icon: 'Box', phase: 'q3', category: 'Creation Studios', vision: 'The metaverse needs faces. XeomX 3D Studio will be the premier destination for creating digital identities and immersive 3D environments.' },
  { slug: 'voice-studio', name: 'Voice Studio', tagline: 'Your voice, amplified by AI', description: 'Clone, create and direct AI voices for any project.', icon: 'Mic', phase: 'q2', category: 'Creation Studios', whyItMatters: 'Voice is the most intimate form of communication. AI voice technology is transforming podcasts, games, films and more.' },
  { slug: 'ar-vr-studio', name: 'AR/VR Preview Studio', tagline: 'Step inside your creations', description: 'Preview and publish augmented and virtual reality experiences.', icon: 'Glasses', phase: 'q3', category: 'Creation Studios', vision: 'Spatial computing is the next platform. XeomX AR/VR Studio will let creators build immersive experiences that blur the line between digital and physical.' },
  { slug: 'production-automation', name: 'Creative Production Automation', tagline: 'Your AI creative director', description: 'Automate entire creative workflows from brief to finished asset.', icon: 'Zap', phase: 'q3', category: 'Creation Studios', vision: 'The future of creative work is human direction + AI execution. Production Automation handles the repetitive so you can focus on the inspired.' },

  { slug: 'model-intelligence', name: 'Model Intelligence', tagline: 'Daily AI benchmarks, live', description: 'Track performance, compare models and always use the best AI for your task.', icon: 'BarChart3', phase: 'q1', category: 'Intelligence & Models', features: ['400+ models tracked', 'Daily benchmarks', 'Task-specific rankings', 'Cost/performance analysis'] },
  { slug: 'ai-compare', name: 'AI Compare Arena', tagline: 'Head-to-head AI battles', description: 'Compare any two AI models side-by-side on your actual prompts.', icon: 'Swords', phase: 'q1', category: 'Intelligence & Models', features: ['Side-by-side output', 'Blind testing mode', 'Community voting', 'Export results'] },
  { slug: 'fine-tuning', name: 'Fine-tuning Studio', tagline: 'Train AI that thinks like you', description: 'Fine-tune foundation models on your data to create specialized AI.', icon: 'Settings2', phase: 'q2', category: 'Intelligence & Models', whyItMatters: 'Generic AI is just the beginning. Fine-tuned models that understand your domain are 10x more valuable.' },
  { slug: 'research-hub', name: 'Research & Deep Analysis Hub', tagline: 'AI-powered research intelligence', description: 'Conduct deep research, synthesize sources and generate insights at scale.', icon: 'Search', phase: 'q2', category: 'Intelligence & Models', whyItMatters: 'Information overload is the challenge of our era. XeomX Research Hub turns the entire web into structured, actionable intelligence.' },
  { slug: 'personalization', name: 'Predictive Personalization Engine', tagline: 'AI that knows what you need next', description: 'Hyper-personalized recommendations that improve with every interaction.', icon: 'Brain', phase: 'q3', category: 'Intelligence & Models', vision: 'The best AI assistant anticipates your needs before you express them. Our personalization engine learns your patterns to deliver exactly what you need.' },
  { slug: 'context-engineering', name: 'Context Engineering Tools', tagline: 'Master the art of AI communication', description: 'Advanced tools for crafting, testing and optimizing AI context and prompts.', icon: 'FileCode', phase: 'q2', category: 'Intelligence & Models', whyItMatters: 'Context is everything in AI. The ability to engineer perfect context is the most valuable skill in the AI era.' },
  { slug: 'multimodal-chat', name: 'Multi-Modal Chat Advanced', tagline: 'Talk to AI in every dimension', description: 'Chat with AI using text, images, audio, video and documents simultaneously.', icon: 'MessageSquare', phase: 'q1', category: 'Intelligence & Models', features: ['Text + image + audio', 'Document analysis', 'Real-time web search', 'Memory across sessions'] },
  { slug: 'local-execution', name: 'Local/On-Device Execution Studio', tagline: 'AI that runs on your machine', description: 'Run powerful AI models locally for complete privacy and zero latency.', icon: 'Cpu', phase: 'q3', category: 'Intelligence & Models', vision: 'Privacy is not optional. On-device AI execution means your data never leaves your machine while still giving you access to powerful intelligence.' },

  { slug: 'prompt-library', name: 'Prompt Library & Version Control', tagline: 'Your prompt arsenal, organized', description: 'Store, version, organize and share your best prompts with powerful management tools.', icon: 'Library', phase: 'q1', category: 'Marketplace & Library', features: ['Version history', 'Folder organization', 'Team sharing', 'Performance tracking'] },
  { slug: 'agent-store', name: 'Agent Store', tagline: 'Deploy AI agents in one click', description: 'Browse, buy and deploy specialized AI agents for any task.', icon: 'Bot', phase: 'q2', category: 'Marketplace & Library', whyItMatters: 'AI agents are the apps of the AI era. The Agent Store will be the App Store of intelligent automation.' },
  { slug: 'knowledge-base', name: 'Knowledge Base / Projects', tagline: 'Your AI memory palace', description: 'Create persistent AI knowledge bases that remember everything about your projects.', icon: 'BookOpen', phase: 'q1', category: 'Marketplace & Library', features: ['Unlimited documents', 'Smart search', 'AI Q&A', 'Team access controls'] },
  { slug: 'asset-library', name: 'Asset Library & Rights Management', tagline: 'Own your AI creations', description: 'Store, manage and monetize all your AI-generated assets with built-in rights management.', icon: 'Image', phase: 'q2', category: 'Marketplace & Library', whyItMatters: 'AI creation is accelerating. Managing, protecting and monetizing creative assets requires a purpose-built system.' },
  { slug: 'template-library', name: 'Template & Preset Library', tagline: 'Start fast, finish strong', description: 'Premium templates and presets for every creative and professional workflow.', icon: 'LayoutTemplate', phase: 'q1', category: 'Marketplace & Library', features: ['500+ templates', 'One-click apply', 'Custom presets', 'Community uploads'] },
  { slug: 'export-center', name: 'Export & Delivery Center', tagline: 'Ship your work anywhere', description: 'Export, format and deliver AI creations to any platform, format or destination.', icon: 'Upload', phase: 'q2', category: 'Marketplace & Library', whyItMatters: 'Creation is only half the journey. Getting your work to the right place in the right format is what makes it real.' },
  { slug: 'docs-ai', name: 'Documentation & Knowledge Base AI', tagline: 'Docs that answer back', description: 'AI-powered documentation that users can query in natural language.', icon: 'FileText', phase: 'q3', category: 'Marketplace & Library', vision: 'The future of documentation is conversational. Instead of searching docs, you ask questions and get instant, accurate answers.' },

  { slug: 'creator-monetization', name: 'Creator Monetization Dashboard', tagline: 'Turn your creativity into income', description: 'Complete dashboard for managing your earnings, sales and creator business on XeomX.', icon: 'DollarSign', phase: 'q2', category: 'Creator Economy', whyItMatters: 'Creators deserve a platform that values their work. XeomX gives creators 70% of every sale — the highest rate in the industry.' },
  { slug: 'creator-payout', name: 'Creator Revenue & Payout System', tagline: 'Get paid, your way', description: 'Flexible payout system with instant transfers, multiple currencies and detailed analytics.', icon: 'Wallet', phase: 'q2', category: 'Creator Economy', whyItMatters: 'Creators in 180+ countries deserve fast, fair payment. Our payout system supports every major currency and payment method.' },
  { slug: 'founders', name: 'Founders / Early Access', tagline: 'The XeomX inner circle', description: 'Exclusive benefits, early access and lifetime perks for XeomX founding members.', icon: 'Crown', phase: 'q1', category: 'Creator Economy', features: ['Lifetime discount', 'Numbered NFT', 'Private Discord', 'Early feature access'] },
  { slug: 'billing', name: 'Billing & Subscription Manager', tagline: 'Complete control over your plan', description: 'Manage subscriptions, credits, invoices and payment methods in one place.', icon: 'CreditCard', phase: 'q1', category: 'Creator Economy', features: ['All plans in one view', 'Usage analytics', 'Invoice history', 'Easy upgrades'] },

  { slug: 'social-feed', name: 'AI Social Feed', tagline: 'The pulse of AI creativity', description: 'Follow creators, discover trending AI work and share your own in a cinematic social feed.', icon: 'Users', phase: 'q2', category: 'Social & Community', whyItMatters: 'AI creation is a social act. Seeing what others build inspires better work and builds the communities that advance the craft.' },
  { slug: 'community', name: 'Community & Collaboration Hub', tagline: 'Build together, grow together', description: 'Spaces for creators to collaborate, share knowledge and build projects together.', icon: 'Globe', phase: 'q2', category: 'Social & Community', whyItMatters: 'The best AI work happens in communities. XeomX Community Hub is where the next generation of AI creators will gather.' },
  { slug: 'viral-sharing', name: 'Viral Sharing & Remix Tools', tagline: 'Create. Share. Go viral.', description: 'One-click sharing tools optimized for maximum reach across every platform.', icon: 'Share2', phase: 'q1', category: 'Social & Community', features: ['Platform-optimized formats', 'Remix with attribution', 'Analytics dashboard', 'Embed anywhere'] },
  { slug: 'trends', name: 'Trend Analysis & Recommendation Hub', tagline: 'Stay ahead of the AI curve', description: 'Real-time trend analysis and personalized recommendations for what AI techniques and tools are rising.', icon: 'TrendingUp', phase: 'q2', category: 'Social & Community', whyItMatters: 'In AI, being early is everything. Our trend engine identifies what will be hot before it hits the mainstream.' },
  { slug: 'governance', name: 'Global Community Governance', tagline: 'The community decides', description: 'Decentralized governance system where the XeomX community shapes the platform\u2019s future.', icon: 'Vote', phase: 'q3', category: 'Social & Community', vision: 'The most powerful platforms are owned by their communities. XeomX Governance will give power to creators, not shareholders.' },
  { slug: 'roadmap', name: 'Roadmap & Feature Voting', tagline: 'Shape the future of XeomX', description: 'Vote on upcoming features, track development progress and see what\u2019s coming next.', icon: 'Map', phase: 'q1', category: 'Social & Community', features: ['Public roadmap', 'Feature voting', 'Status updates', 'Beta sign-ups'] },

  { slug: 'collaboration', name: 'Real-time Collaboration Canvas', tagline: 'Create together, in real time', description: 'Multiple creators working on the same AI project simultaneously, like Figma for AI.', icon: 'Users2', phase: 'q2', category: 'Collaboration & Workflow', whyItMatters: 'The best AI work is collaborative. Real-time collaboration removes the friction of working together on complex AI projects.' },
  { slug: 'team-workspace', name: 'Team Collaboration Workspace', tagline: 'Your team\u2019s AI command center', description: 'Shared workspaces for teams to organize, collaborate and manage AI projects together.', icon: 'Building2', phase: 'q2', category: 'Collaboration & Workflow', whyItMatters: 'Teams need shared context, shared tools and shared results. XeomX Team Workspace is built for how modern teams actually work.' },
  { slug: 'ai-agents', name: 'AI Agents & Autonomous Workflows', tagline: 'Set it. Let AI handle it.', description: 'Deploy autonomous AI agents that work 24/7 on complex, multi-step tasks.', icon: 'BotMessageSquare', phase: 'q2', category: 'Collaboration & Workflow', whyItMatters: 'Agentic AI is the biggest shift in productivity since the internet. Autonomous workflows will free humans for higher-level creative work.' },
  { slug: 'version-control', name: 'Version Control Global', tagline: 'Git for your AI work', description: 'Full version history, branching and rollback for all your AI projects and prompts.', icon: 'GitMerge', phase: 'q2', category: 'Collaboration & Workflow', whyItMatters: 'Professional AI work requires professional tools. Version control ensures you never lose great work and can always go back.' },
  { slug: 'human-loop', name: 'Human-in-the-Loop Manager', tagline: 'AI does the work. You make the calls.', description: 'System for reviewing, approving and directing AI actions before they execute.', icon: 'ShieldCheck', phase: 'q3', category: 'Collaboration & Workflow', vision: 'The most powerful AI systems keep humans in control. Human-in-the-Loop Manager ensures AI works for you, not the other way around.' },

  { slug: 'enterprise-admin', name: 'Enterprise Admin & Security', tagline: 'Platform control at scale', description: 'Complete admin tools for managing XeomX at enterprise scale \u2014 users, permissions, policies.', icon: 'Shield', phase: 'q2', category: 'Admin & Enterprise', whyItMatters: 'Enterprise adoption requires enterprise-grade controls. XeomX Enterprise gives IT teams the tools they need to deploy safely at scale.' },
  { slug: 'privacy-compliance', name: 'Data Privacy & Compliance', tagline: 'Your data. Your rules.', description: 'GDPR, CCPA and global compliance tools with full data sovereignty controls.', icon: 'Lock', phase: 'q3', category: 'Admin & Enterprise', vision: 'Privacy regulation is accelerating globally. XeomX Compliance Center will make it effortless to meet every regional data protection requirement.' },
  { slug: 'audit-log', name: 'Audit & Governance Log', tagline: 'Complete accountability, always', description: 'Immutable audit log of every action on the platform for compliance and security.', icon: 'ClipboardList', phase: 'q3', category: 'Admin & Enterprise', vision: 'Enterprise trust requires complete transparency. Every action, every change, every access \u2014 logged and queryable forever.' },
  { slug: 'sso', name: 'SSO & Identity Management', tagline: 'One login. Everything unlocked.', description: 'Enterprise SSO integration with SAML, OIDC and all major identity providers.', icon: 'KeyRound', phase: 'q2', category: 'Admin & Enterprise', whyItMatters: 'Enterprise security starts with identity. SSO integration means one login for everything, with zero security compromises.' },
  { slug: 'security', name: 'Security Threat Detection', tagline: 'Always protected, always watching', description: 'Real-time threat detection and automated response to keep the platform secure.', icon: 'AlertTriangle', phase: 'q3', category: 'Admin & Enterprise', vision: 'AI platforms are high-value targets. XeomX Security uses AI to fight AI-powered threats in real time.' },
  { slug: 'cost-control', name: 'Cost Transparency & Budget Control', tagline: 'Know exactly what you spend', description: 'Complete cost visibility and budget controls for teams and enterprises using XeomX.', icon: 'PieChart', phase: 'q2', category: 'Admin & Enterprise', whyItMatters: 'AI costs can spiral quickly. XeomX Cost Control gives teams complete visibility and hard limits on AI spending.' },
  { slug: 'api-quota', name: 'API Rate Limit & Quota Manager', tagline: 'Control your API usage at scale', description: 'Granular API rate limiting and quota management for teams and enterprise deployments.', icon: 'Gauge', phase: 'q2', category: 'Admin & Enterprise', whyItMatters: 'Reliable API access requires smart quota management. XeomX ensures fair, predictable access for all users.' },
  { slug: 'backup', name: 'Backup & Recovery System', tagline: 'Your work, always safe', description: 'Automated backup and instant recovery for all your XeomX projects and data.', icon: 'HardDrive', phase: 'q3', category: 'Admin & Enterprise', vision: 'Data loss is catastrophic. XeomX Backup ensures every project, every prompt, every creation is always recoverable.' },

  { slug: 'settings', name: 'Global Settings & Personalization', tagline: 'Make XeomX yours', description: 'Complete platform customization \u2014 theme, language, notifications, AI preferences and more.', icon: 'Settings', phase: 'q1', category: 'Platform & Settings', features: ['Theme customization', 'AI model preferences', 'Notification controls', 'Language settings'] },
  { slug: 'profile', name: 'Profile & Billing', tagline: 'Your XeomX identity', description: 'Manage your profile, portfolio, billing and account settings.', icon: 'User', phase: 'q1', category: 'Platform & Settings', features: ['Public profile', 'Portfolio showcase', 'Billing history', 'Subscription management'] },
  { slug: 'mobile-pwa', name: 'Mobile PWA / Native View', tagline: 'XeomX in your pocket', description: 'Full-featured mobile experience optimized for on-the-go AI creation.', icon: 'Smartphone', phase: 'q2', category: 'Platform & Settings', whyItMatters: 'Creativity happens everywhere. XeomX Mobile brings the full power of the platform to every device.' },
  { slug: 'integrations', name: 'Integrations & API Portal', tagline: 'Connect everything', description: 'Connect XeomX to your entire tool stack with native integrations and a powerful API.', icon: 'Plug', phase: 'q1', category: 'Platform & Settings', features: ['100+ integrations', 'REST & GraphQL API', 'Webhooks', 'SDK libraries'] },
  { slug: 'accessibility', name: 'Accessibility & Inclusion Tools', tagline: 'AI for everyone', description: 'Full accessibility support ensuring XeomX is usable by everyone, regardless of ability.', icon: 'Accessibility', phase: 'q3', category: 'Platform & Settings', vision: 'AI should have no barriers. XeomX Accessibility ensures every feature is available to every user.' },
  { slug: 'localization', name: 'Multi-Language & Localization Studio', tagline: 'XeomX speaks your language', description: 'Full platform localization with AI-powered translation for 50+ languages.', icon: 'Languages', phase: 'q3', category: 'Platform & Settings', vision: 'AI creativity is a global phenomenon. XeomX will be fully accessible in every major language.' },
  { slug: 'performance', name: 'Performance Monitoring Dashboard', tagline: 'See how your AI performs', description: 'Real-time performance analytics for all your AI workflows and deployments.', icon: 'Activity', phase: 'q2', category: 'Platform & Settings', whyItMatters: 'You can\u2019t improve what you don\u2019t measure. XeomX Performance gives you complete visibility into how your AI work is performing.' },
  { slug: 'analytics', name: 'Advanced Analytics Dashboard', tagline: 'Intelligence about your intelligence', description: 'Deep analytics across all platform activity \u2014 usage, costs, performance and impact.', icon: 'LineChart', phase: 'q2', category: 'Platform & Settings', whyItMatters: 'Data-driven decisions require data. XeomX Analytics gives you the complete picture of how AI is working for you.' },
  { slug: 'super-app-hub', name: 'Global Super App Hub', tagline: 'The center of the AI universe', description: 'The master control panel connecting every XeomX capability in one unified view.', icon: 'Globe2', phase: 'q3', category: 'Platform & Settings', vision: 'XeomX is more than an app \u2014 it\u2019s the infrastructure for the AI era. The Super App Hub will be the bridge between every tool, every model, every creator.' },

  { slug: 'academy', name: 'Academy / Learning Hub', tagline: 'Master the AI era', description: 'Structured courses, tutorials and certifications for every level of AI practitioner.', icon: 'GraduationCap', phase: 'q2', category: 'Support & Growth', whyItMatters: 'The AI skills gap is massive. XeomX Academy will be the premier destination for learning to work effectively with AI.' },
  { slug: 'safety', name: 'Safety, Moderation & Local Tools', tagline: 'AI you can trust', description: 'Comprehensive content moderation and safety tools to ensure responsible AI use.', icon: 'ShieldAlert', phase: 'q2', category: 'Support & Growth', whyItMatters: 'Responsible AI is not optional. XeomX Safety ensures the platform remains a positive, trustworthy environment for all users.' },
  { slug: 'support', name: 'Support Center with AI Agent', tagline: 'Help that actually helps', description: 'AI-powered support that resolves issues instantly, backed by human experts for complex cases.', icon: 'Headphones', phase: 'q1', category: 'Support & Growth', features: ['AI instant answers', 'Live chat', 'Video tutorials', '24/7 availability'] },
  { slug: 'feedback', name: 'User Feedback & Improvement Loop', tagline: 'Your voice shapes XeomX', description: 'Structured system for submitting, tracking and seeing your feedback implemented.', icon: 'MessageCircle', phase: 'q1', category: 'Support & Growth', features: ['Feature requests', 'Bug reporting', 'Progress tracking', 'Community voting'] },
  { slug: 'beta', name: 'Beta Testing & Early Access Portal', tagline: 'Be first. Shape the future.', description: 'Get early access to upcoming XeomX features before they launch to the public.', icon: 'FlaskConical', phase: 'q1', category: 'Support & Growth', features: ['Priority access', 'Beta tester badge', 'Direct feedback channel', 'Exclusive previews'] },
];

export function getSection(slug: string): ExploreSection | undefined {
  return [...CORE_SECTIONS, ...EXPLORE_SECTIONS].find((s) => s.slug === slug);
}

export function getPhaseBadge(phase: SectionPhase): { label: string; className: string } {
  switch (phase) {
    case 'live':
      return { label: 'Live', className: 'bg-emerald-500/15 text-emerald-300 border-emerald-400/30' };
    case 'q1':
      return { label: 'Q1 2026', className: 'bg-amber-400/15 text-amber-200 border-amber-300/30' };
    case 'q2':
      return { label: 'Q2 2026', className: 'bg-fuchsia-500/15 text-fuchsia-200 border-fuchsia-400/30' };
    case 'q3':
      return { label: 'Q3 2026', className: 'bg-white/5 text-muted-foreground border-white/10' };
  }
}

export function getCoreLink(slug: string): string {
  if (slug === 'login') return '/auth';
  if (slug === 'dashboard') return '/dashboard';
  if (slug === 'home') return '/';
  return '/';
}