/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromptIdRouteImport } from './routes/prompt.$id'
import { Route as ExploreSlugRouteImport } from './routes/explore_.$slug'
import { Route as CollectionsIdRouteImport } from './routes/collections.$id'

const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptIdRoute = PromptIdRouteImport.update({
  id: '/prompt/$id',
  path: '/prompt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreSlugRoute = ExploreSlugRouteImport.update({
  id: '/explore_/$slug',
  path: '/explore/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIdRoute = CollectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CollectionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/creators': typeof CreatorsRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/prompt/$id': typeof PromptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/creators': typeof CreatorsRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/prompt/$id': typeof PromptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/creators': typeof CreatorsRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/explore_/$slug': typeof ExploreSlugRoute
  '/prompt/$id': typeof PromptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/collections'
    | '/creators'
    | '/dashboard'
    | '/explore'
    | '/feed'
    | '/collections/$id'
    | '/explore/$slug'
    | '/prompt/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/collections'
    | '/creators'
    | '/dashboard'
    | '/explore'
    | '/feed'
    | '/collections/$id'
    | '/explore/$slug'
    | '/prompt/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/collections'
    | '/creators'
    | '/dashboard'
    | '/explore'
    | '/feed'
    | '/collections/$id'
    | '/explore_/$slug'
    | '/prompt/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  CreatorsRoute: typeof CreatorsRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  FeedRoute: typeof FeedRoute
  ExploreSlugRoute: typeof ExploreSlugRoute
  PromptIdRoute: typeof PromptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt/$id': {
      id: '/prompt/$id'
      path: '/prompt/$id'
      fullPath: '/prompt/$id'
      preLoaderRoute: typeof PromptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore_/$slug': {
      id: '/explore_/$slug'
      path: '/explore/$slug'
      fullPath: '/explore/$slug'
      preLoaderRoute: typeof ExploreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$id': {
      id: '/collections/$id'
      path: '/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdRouteImport
      parentRoute: typeof CollectionsRoute
    }
  }
}

interface CollectionsRouteChildren {
  CollectionsIdRoute: typeof CollectionsIdRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsIdRoute: CollectionsIdRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  CreatorsRoute: CreatorsRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  FeedRoute: FeedRoute,
  ExploreSlugRoute: ExploreSlugRoute,
  PromptIdRoute: PromptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
